CREATE SCHEMA IF NOT EXISTS CT;

DROP TABLE IF EXISTS CT.TRIALS CASCADE;
CREATE TABLE CT.TRIALS (
  NCT_ID            VARCHAR(20)   NOT NULL,
  INDICATION        VARCHAR(20),
  BRIEF_TITLE       VARCHAR(2000),
  OVERALL_STATUS    VARCHAR(60),
  STUDY_TYPE        VARCHAR(40),
  -- PHASE is normalised and NEVER null: ~22% of trials carry no phase at all and
  -- 'UNKNOWN' keeps them queryable instead of silently dropping them from a
  -- WHERE PHASE = 'PHASE3'. PHASE_RAW preserves what the registry actually said.
  PHASE             VARCHAR(40)   NOT NULL,
  PHASE_RAW         VARCHAR(60),
  LEAD_SPONSOR      VARCHAR(500),
  SPONSOR_CLASS     VARCHAR(40),
  ENROLLMENT        DECIMAL(18,0),
  START_DATE        VARCHAR(20),
  MIN_AGE_YEARS     DECIMAL(9,3),
  MAX_AGE_YEARS     DECIMAL(9,3),
  SEX               VARCHAR(20),
  HEALTHY_VOLUNTEERS VARCHAR(10),
  ELIG_CHARS        DECIMAL(18,0),
  ELIGIBILITY_TEXT  VARCHAR(2000000)
);

DROP TABLE IF EXISTS CT.TRIAL_CONDITIONS CASCADE;
CREATE TABLE CT.TRIAL_CONDITIONS (NCT_ID VARCHAR(20), CONDITION_NAME VARCHAR(1000));

DROP TABLE IF EXISTS CT.TRIAL_COUNTRIES CASCADE;
CREATE TABLE CT.TRIAL_COUNTRIES (NCT_ID VARCHAR(20), COUNTRY VARCHAR(200));

DROP TABLE IF EXISTS CT.TRIAL_OUTCOMES CASCADE;
CREATE TABLE CT.TRIAL_OUTCOMES (
  NCT_ID VARCHAR(20), SEQ DECIMAL(9,0), OUTCOME_KIND VARCHAR(20),
  MEASURE VARCHAR(4000), TIME_FRAME VARCHAR(2000));

DROP TABLE IF EXISTS CT.TRIAL_ARMS CASCADE;
CREATE TABLE CT.TRIAL_ARMS (
  NCT_ID VARCHAR(20), SEQ DECIMAL(9,0),
  -- 'UNSPECIFIED' where the registry coded no type, so "no coded comparator"
  -- is a queryable state rather than a NULL to be guessed at.
  ARM_TYPE VARCHAR(40), ARM_LABEL VARCHAR(2000));

DROP TABLE IF EXISTS CT.TRIAL_INTERVENTIONS CASCADE;
CREATE TABLE CT.TRIAL_INTERVENTIONS (
  NCT_ID VARCHAR(20), SEQ DECIMAL(9,0),
  INTERVENTION_TYPE VARCHAR(60), INTERVENTION_NAME VARCHAR(2000));

DROP TABLE IF EXISTS CT.ELIG_CHUNKS CASCADE;
CREATE TABLE CT.ELIG_CHUNKS (
  NCT_ID VARCHAR(20), CHUNK_ID DECIMAL(9,0),
  -- INCLUSION / EXCLUSION / UNKNOWN, recovered from prose headings. The registry
  -- has no structured field for this; 97.3% of chunks resolve to a definite one.
  CRITERION_SECTION VARCHAR(20), CHUNK_TEXT VARCHAR(200000));
