DROP TABLE IF EXISTS CT.ELIG_VECTORS CASCADE;
-- Long and narrow, ONE ROW PER DIMENSION, because Exasol has no array type and
-- no native vector type. Vectors are L2-normalised at build time, so cosine
-- similarity is SUM(a.VAL * b.VAL) -- an ordinary join and GROUP BY, which is
-- exactly the shape MPP is good at.
CREATE TABLE CT.ELIG_VECTORS (
  NCT_ID VARCHAR(20), CHUNK_ID DECIMAL(9,0), DIM DECIMAL(9,0), VAL DOUBLE);

DROP TABLE IF EXISTS CT.CHUNK_TOKENS CASCADE;
CREATE TABLE CT.CHUNK_TOKENS (
  NCT_ID VARCHAR(20), CHUNK_ID DECIMAL(9,0), TERM VARCHAR(200), TF DECIMAL(9,0));

DROP TABLE IF EXISTS CT.TERM_IDF CASCADE;
CREATE TABLE CT.TERM_IDF (TERM VARCHAR(200), DF DECIMAL(18,0), IDF DOUBLE);

DROP TABLE IF EXISTS CT.CHUNK_LEN CASCADE;
CREATE TABLE CT.CHUNK_LEN (NCT_ID VARCHAR(20), CHUNK_ID DECIMAL(9,0), LEN DECIMAL(9,0));
